name: MageSpellsRemastered
version: 2.0.3-SNAPSHOT
description: Delve into the black magics of minecraft!
author: L2_Envy
main: me.L2_Envy.MSRM.Main
depend: [TitleManager, Vault]
softdepend: [WorldGuard, WorldEdit]
commands:
    mage:
        aliases: [magespells, ms]
        description: Command menu for MageSpells Remastered.
        usage: /<command>