name: MageSpellsRemastered
version: 2.0.6.4-SNAPSHOT
description: Delve into the black magics of minecraft!
author: L2_Envy
main: me.L2_Envy.MSRM.Main
depend: [TitleManager]
softdepend: [WorldGuard, WorldEdit]
commands:
    mage:
        aliases: [magespells, ms]
        description: Command menu for MageSpells Remastered.
        usage: /<command>
    tc:
        aliases: [teamchat]
        description: Talk in your team chat!
        usage: /<command> <message>
permissions:
   magespells.*:
      description: Gives access to all MageSpell features.
      children:
        magespells.mage: true
        magespells.spell: true
        magespells.wand: true
   magespells.spell.*:
      children:
        magespells.spell: true
   magespells.wand.*:
      children:
        magespells.wand: true
   magespells.mage:
      description: Enables mana bar for mages.
      default: op
   magespells.spell:
      description: Specific per spell
      default: op
   magespells.wand:
      description: Specific per wand
      default: op
